version: '3.8'

services:
  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - user_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  user-service:
    build: .
    env_file:
      - .env
    depends_on:
      user-db:
        condition: service_healthy
    ports:
      - "2025:2025"
    volumes:
      - ./:/app:cached
      - /app/node_modules

volumes:
  user_pg:
